In [2]:
#QUESTION (1)
import numpy as np
array1=np.arange(2,50,3)
print(array1)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [16]:
#QUESTION (2)
import numpy as np
list1=[1,9,3,8,5]
list2=[6,18,8,12,0]
#converting lists to arrays
array1=np.array(list1)
array2=np.array(list2)
print(array1)
print(array2)
#concatenate the arrays
arr=np.concatenate((array1,array2))
print(arr)
#sort the arrays
print(np.sort(arr))

[1 9 3 8 5]
[ 6 18  8 12  0]
[ 1  9  3  8  5  6 18  8 12  0]
[ 0  1  3  5  6  8  8  9 12 18]


In [21]:
#QUESTION (3)
import numpy as np
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array1)
#dimensions of ndarray 
print(array1.shape)
#size
print(array1.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9


In [51]:
#QUESTION (4)
import numpy as np
#Use numpy. reshape() to reshape a 1D NumPy array to a 2D NumPy array.
array11=np.array([1,2,3,4,5,6])
print(array11)
print(array11.reshape(2,3))

#np.newaxis  , np.expand_dims
array2=np.arange(9)
print(array2)
print(array2[:, np.newaxis])


x = np.zeros((3, 4)) 
y = np.expand_dims(x, axis=1).shape 
print(y) 

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[0 1 2 3 4 5 6 7 8]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
(3, 1, 4)


In [57]:
#QUESTION (5)
import numpy as np
array22=np.array([[11,22,33],[44,55,66]])
array33=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array22)


#vstack,hstack
print(np.hstack(array22))
print(np.vstack(array22))

print(array33)
print(np.hstack(array33))
print(np.vstack(array33))

[[11 22 33]
 [44 55 66]]
[11 22 33 44 55 66]
[[11 22 33]
 [44 55 66]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [124]:
#QUESTION (6)
import numpy as np
list1=['abc','pqr','abc','pqr','efg']
print(list1)

# to get unique items and counts of unique items
print(list1.count('abc'))
np.unique(list1)

['abc', 'pqr', 'abc', 'pqr', 'efg']
2


array(['abc', 'efg', 'pqr'], dtype='<U3')